# configs/config_ddqn.yaml
# Double Deep Q-Learning
gamma              : 0.99
batch_size         : 128
epsilon            : 1.0
epsilon_min        : 0.01
epsilon_decay      : 0.9995
buffer_size        : 50000
lr                 : 6.113e-3
target_update_freq : 1947